version: '3.5'

services:
  rest-db:
    image: postgres
    container_name: rest_app_alishev-db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=rest_app_alishev_db
    ports:
      - "5801:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data